### ISSUE TITLE
the problem  when I build it

### ISSUE THREAD

**Issue by guluglu** [michaelgibson/heka-encoder-filter#1]
In the step of Build Heka: . ./build.sh,I met:
# github.com/michaelgibson/heka-encoder-filter

heka/src/github.com/michaelgibson/heka-encoder-filter/encoder_filter.go:58: multiple-value h.PipelinePack() in single-value context
heka/src/github.com/michaelgibson/heka-encoder-filter/encoder_filter.go:76: not enough arguments in call to pack.Recycle
make[2]: **\* [CMakeFiles/hekad] Error 2
make[1]: **\* [CMakeFiles/hekad.dir/all] Error 2
make: **\* [all] Error 2

Maybe the version of heka result in it?
: )

**Comment by michaelgibson** [comment]
There have been significant changes to the plugin API's since this was created.
http://hekad.readthedocs.org/en/latest/developing/plugin.html#transitional-filter-output-apis-for-v0-10-only

I've last built this against v0.9.2 successfully.
Anything beyond that will require refactoring for the new plugin API

**Comment by guluglu** [comment]
thanks very much : )

**Comment by guluglu** [comment]
@michaelgibson Hi,I'm sorry to bother you again,I want to ask you another question for help.When I checkout brach to v0.9,source build.sh will met error:make: **\* No targets specified and no makefile found.Would you like to give some suggestions?

**Comment by michaelgibson** [comment]
Not sure.
That message can be the result of several different potential issues:
https://github.com/mozilla-services/heka/search?q=No+targets+specified&type=Issues&utf8=%E2%9C%93

I experienced a similar error here:
https://github.com/mozilla-services/heka/issues/404#issuecomment-23951346
My issue was due to an older version of cmake.

I also run ". ./build.sh" instead of "source ./build.sh"
Not sure if that makes a difference.

In any case I don't believe your issue is related to this plugin.
Good luck!

**Comment by michaelgibson** [comment]
This is solved by issue https://github.com/michaelgibson/heka-encoder-filter/issues/2
